name: Build and Test

on:
  push:
    branches:
      - main
      - master
      - develop
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go Linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          go test ./... -v -coverprofile=coverage/coverage.out
          go tool cover -html=coverage/coverage.out -o coverage/coverage.html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          file: ./coverage/coverage.out
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build binaries for testing
        run: make build-all

      - name: Install Expect
        run: sudo apt-get install -y expect

      - name: Run terminal-based tests with Expect
        run: |
          chmod +x tests/expect_test.sh
          ./tests/expect_test.sh
