name: GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binaries
        run: make build-all

      - name: Zip binaries
        run: |
          mkdir -p release
          cd bin
          zip -r ../release/cub-binaries-${GITHUB_REF_NAME}.zip ./*
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Calculate SHA256
        id: sha256
        run: |
          echo "HASH=$(sha256sum release/cub-binaries-${GITHUB_REF_NAME}.zip | awk '{ print $1 }')" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ACC_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }}
            Automated release generated by GitHub Actions.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ACC_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/cub-binaries-${{ github.ref_name }}.zip
          asset_name: cub-binaries-${{ github.ref_name }}.zip
          asset_content_type: application/zip
